name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: registry.lahs.club
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.lahs.club/publish:latest
